package com.ashapiro.catanserver.enums;

public enum EventType {
    BROADCAST_USER_DISCONNECTED,
    BROADCAST_USER_CONNECTED,
    BROADCAST_START_GAME,
    BROADCAST_NEW_HOST,
    BROADCAST_USER_READY_AND_LOAD,
    BROADCAST_USER_TURN,
    BROADCAST_BUILD_ROAD,
    BROADCAST_BUILD_HOUSE,
    BROADCAST_GIVE_RESOURCE,
    REQUEST_CONNECT,
    REQUEST_START_GAME,
    REQUEST_BUILD_ROAD,
    REQUEST_READY_AND_LOAD,
    REQUEST_BUILD_HOUSE,
    RESPONSE_CONNECT,
    RESPONSE_START_GAME
}
